# Generated by Django 4.2.2 on 2023-06-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('e_commerce_app', '0007_remove_item_quantity_orderitem_quantity'),
    ]

    operations = [
    ]
